apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: exporter-telexporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    role: alcide-alert-rules
  name: exporter-telexporter
spec:
  groups:
  {{- include "agent.rules.yaml.tpl" . | indent 2}}
  {{- include "alcide-infra.rules.yaml.tpl" . | indent 2}}
  {{- include "monitors.rules.yaml.tpl" . | indent 2}}
  {{- include "server.rules.yaml.tpl" . | indent 2}}
  {{- include "reputation.rules.yaml.tpl" . | indent 2}}