{{- if and .Values.alertmanager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-{{ template "prometheus-operator.fullname" . }}-alertmanager
  labels:
    app: {{ template "prometheus-operator.name" . }}-alertmanager
{{ include "prometheus-operator.labels" . | indent 4 }}
data:
  {{ if eq .Values.alertmanager.envType "internal" }}
  alertmanager.yaml: {{ toYaml .Values.alertmanager.internalConfig | b64enc | quote }}
  {{ else if eq .Values.alertmanager.envType "production" }}
  alertmanager.yaml: {{ toYaml .Values.alertmanager.productionConfig | b64enc | quote }}
  {{- end }}
{{- range $key, $val := .Values.alertmanager.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}